# Generated by Django 4.1.7 on 2023-05-15 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0005_alter_members_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='end_date',
            field=models.DateField(default=datetime.date(2023, 1, 31)),
        ),
    ]
