# Generated by Django 4.1.7 on 2023-05-19 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0007_alter_members_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='middle_name',
        ),
    ]
