# Generated by Django 4.1.7 on 2023-05-28 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0009_alter_members_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='address',
        ),
        migrations.RemoveField(
            model_name='members',
            name='gender',
        ),
    ]
